# Generated by Django 3.2.4 on 2021-06-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.CharField(max_length=200)),
                ('finalizado', models.CharField(choices=[('Finalizado', 'Finalizado'), ('Lendo', 'Lendo')], default='Lendo', max_length=20)),
                ('resumo', models.TextField()),
                ('adicionado', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['adicionado'],
            },
        ),
    ]
